### ISSUE TITLE
./slotmashine.hpp:12:10: fatal error: 'ncursesw/ncurses.h' file not found

### ISSUE THREAD

**Issue by nyngwang** [derDere/slot-machine#1]
What should I do? I'm on macOS. Tried brew install `ncurses` but it didn't work.

```
✔ ~/GitHub/slot-machine % make install                                                                                                                                                                                    22:47:04
g++ -o "slot-machine" main.cpp slotmashine.cpp slotmashineview.cpp -lncursesw -std=c++17
main.cpp:9:10: fatal error: 'ncursesw/ncurses.h' file not found
#include <ncursesw/ncurses.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
In file included from slotmashine.cpp:4:
./slotmashine.hpp:12:10: fatal error: 'ncursesw/ncurses.h' file not found
#include <ncursesw/ncurses.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
slotmashineview.cpp:4:10: fatal error: 'ncursesw/ncurses.h' file not found
#include <ncursesw/ncurses.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** ["slot-machine"] Error 1
```

**Comment by sys-256** [comment]
I'm on Linux. I ran `ls /usr/include | grep curses` to see where my ncurses headers were. For me it was `/usr/include/ncurses.h`, not `/usr/include/ncursesw/ncurses.h`, so I changed all `ncursesw/ncurses.h` in the source to `ncurses.h`, which worked.

Not sure how it works on MacOS though, but I guess you can try something similar (like the last step I did).

**Comment by nyngwang** [comment]
🥲 ... macOS users have been forgotten.

```zsh
✔ ~ % ls /usr/include | grep curses                                                                                                                                                                                        0:14:22
ls: /usr/include: No such file or directory
```

**Comment by iQuickDev** [comment]
if you're on debian

```
sudo apt-get install libncurses5-dev libncursesw5-dev
```

**Comment by patillacode** [comment]
I am trying to make it work in macOS, so far I have done this:

```bash
# install ncurses via brew
$ brew install ncurses
```

Like @sys-256 mentioned, I replaced all occurrences of `ncursesw/ncurses.h` in the source code for the specific path in my system: `/usr/local/Cellar/ncurses/6.4/include/ncursesw/ncurses.h`

It still breaks in a similar manner:
```
g++ -o "slot-machine" main.cpp slotmashine.cpp slotmashineview.cpp -lncursesw -std=c++17
In file included from main.cpp:9:
/usr/local/Cellar/ncurses/6.4/include/ncursesw/curses.h:89:10: fatal error: 'ncursesw/ncurses_dll.h' file not found
```

There are no references in the source to `ncursesw/ncurses_dll.h` as far as I can tell, am I right?

So is it my `ncurses` installation that is not working?
Any thoughts?

**Comment by patillacode** [comment]
Found a fix for Mac:

Install ncurses with `brew install ncurses`
Then add `-I/usr/local/opt/ncurses/include -L/usr/local/opt/ncurses/lib` to the `Makefile` in line 8 so this:

```makefile
$(APP): $(SRC)
	g++ -o $(APP) $(SRC) -lncursesw -std=c++17
```

becomes this:

``` makefile

$(APP): $(SRC)
	g++ -o $(APP) $(SRC) -I/usr/local/opt/ncurses/include -L/usr/local/opt/ncurses/lib -lncursesw -std=c++17

```

Then `make install` will work (this [SO answer](https://stackoverflow.com/questions/56622042/clang-on-macos-fails-linking-lmenu-from-ncurses) helped me)

![Screenshot 2023-06-01 at 17 11 17](https://github.com/derDere/slot-machine/assets/10074977/f2110148-49f5-4037-8d61-6f3c62e546b2)


Now i just need to know which font has all the icons, as you can see I am missing some.

Any clues?

**Comment by rohanb1216** [comment]
I'm using a nerd-font patched jetbrains mono, usually any terminal application with fancy icons uses nerd font versions of a font. 
[Found Here](https://www.nerdfonts.com/)

**Comment by derDere** [comment]
Hi, please be sure to install your c++ libaries for ncursesw (N and W are important) the code is not to fancy so the almost newest version should work.

Also be sure that your terminal is able to display all emojis. Most emojies are two chars in width so if they arent included in the font there will be miss alignments.
