### ISSUE TITLE
Integer overflow with amount of coins

### ISSUE THREAD

**Issue by sys-256** [derDere/slot-machine#2]
When manually changing the amount of coins in `~/.config/slot-machine/default` (or any other profile name) to anything over the 32 bit integer limit (>2,147,483,647), it overflows, and the amount of coins goes back to 2,147,483,647. The value in the config isn't overwritten, however.

Upon winning, and thereby making the amount of coins go over 2,147,483,647 while in game, something much weirder happened. (I think I was at 2,147,483,643 when clicking the space bar): 
![image](https://github.com/derDere/slot-machine/assets/84628826/34f77c2a-c3c2-4af5-ba39-7d4c86c67a1f)

The relation between these numbers seems to be that `100-2,147,483,6434=-2,147,483,544` (amount of coins in the config file), and the amount of coins shown on screen is just that, but with the first 3 characters removed (`-21`).

I realize that it'll be very hard to reach more than 2 billion coins when playing this (without modifying the config file), but it might be fun to look into this if you're interested.

A possible solution would be changing the data type from `int` to `long long`, or possibly `unsigned long long` if it is ensured that that amount of coins can't go negative, nor overflow and become negative that way. Which would respectively increase the maximum amount to `9223372036854775807` or `18446744073709551615`, which is a lot harder to achieve.

**Comment by derDere** [comment]
Congratulations. That's no bug its a feature called: The error price for all who are to good for this game. I love that your analyseing this game that much xD but I wont change that. The config file is not meant to be changed manually. But feel free to creatively break this program as much as possible.
